

import { ThemeProvider } from "@/components/theme-provider"


export const metadata = {
  title: 'Zero Infinite',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
     
          
            {children}
          
        
        </ThemeProvider>
     
        </body>
    </html>
  )
}
